### ISSUE TITLE
MonoPatBinds prevents building with GHC 9.2

### ISSUE THREAD

**Issue by cdsmith** [haskell-hvr/regex-tdfa#23]
Even with `cabal build --allow-newer`, cabal will not build regex-tdfa using GHC 9.2. The reason is that it specifies `-XNoMonoPatBinds` as a default extension in the cabal file. This has had no effect since GHC 7.4, and has finally been removed in GHC 9.2.

**Comment by andreasabel** [comment]
I prepared PR #24 to fix this.

I can't test this at the moment as 
- I cannot install GHC 9.2 due to https://gitlab.haskell.org/ghc/ghc/-/issues/19734
- Haskell CI does not test against HEAD: https://github.com/haskell-CI/haskell-ci/issues/460

@cdsmith: Would you mind testing this for me before I release it?

**Comment by andreasabel** [comment]
I released [1.3.1.1 on hackage](https://hackage.haskell.org/package/regex-tdfa-1.3.1.1).

**Comment by andreasabel** [comment]
I tested now with GHC 9.2 alpha2.
