### ISSUE TITLE
Brackets inside a Bracket Expression are not handled properly

### ISSUE THREAD

**Issue by drsooch** [haskell-hvr/regex-tdfa#30]
Attempting to add brackets inside a bracket expression seems to act differently based on the ordering. I spent a majority of my time attempting to escape the brackets (`\\[`) with no luck. Below I've provided a few variations on the same expression showcasing the issue. 

I'm not extremely familiar with the various flavors of Regex, but this doesn't seem correct.

```
*ghci> ("Expected type: [Int] -> Int" :: Text) =~ "Expected type: ([[]a-zA-Z0-9 ->]+)" :: Bool
False
*ghci> ("Expected type: [Int] -> Int" :: Text) =~ "Expected type: ([][a-zA-Z0-9 ->]+)" :: Bool
True
*ghci> ("Expected type: [Int] -> Int" :: Text) =~ "Expected type: ([\\[\\]a-zA-Z0-9 ->]+)" :: Bool
False
```

**Comment by andreasabel** [comment]
It seems like inside `[...]`, the escaping via `\` does not work.  A backslash inside brackets is just the backslash character.  So, you cannot put `]` inside brackets, as it closes the brackets.  (Putting `]` inside is fine.)  
There is one exception though: You can put `]` as the _first_ character inside brackets, because empty brackets are not allows (parse error).  This is why your second try works:
```
ghci> "Expected type: [Int] -> Int" =~ "^Expected type: ([][a-zA-Z0-9 ->]+)$" :: Bool
True
```
Does this help?

**Comment by andreasabel** [comment]
@drsooch 
> Curious, shouldn't escaping work inside brackets?

I suppose so, but is it universally the case?  What would be the references?

Btw, I wonder why the regex-* package family does not expose an abstract syntax for regexes (regex expression trees).  It would maybe tedious to write down the ASTs, but at least you would not have to battle with escaping and hard-to-comprehend parsers for regexes...

**Comment by drsooch** [comment]
I just noticed the link you pasted and took a look. Also looks like there is a specific example of escaped brackets (granted they are not being used inside a bracket expression). Thanks again!
