### ISSUE TITLE
Wrong render of the regular expression string in the Basics tutorial

### ISSUE THREAD

**Issue by s-and-witch** [haskell-hvr/regex-tdfa#50]
Here https://hackage.haskell.org/package/regex-tdfa-1.3.2/docs/Text-Regex-TDFA.html in Basics section first regular expression rendered by haddock as 
```
>>> let emailRegex = "[a-zA-Z0-9+._-]+\[-a-zA-Z]+\.[a-z]+"
```
But that's not a valid Haskell string, it should be
```
let emailRegex = "[a-zA-Z0-9+._-]+\\@[-a-zA-Z]+\\.[a-z]+"
```

Perhaps you need to add more slashes or something

**Comment by andreasabel** [comment]
The source gives a correct Haskell string: https://github.com/haskell-hvr/regex-tdfa/blob/693a7f8e8df9a472e63ccb80afacc7e94138d6b8/lib/Text/Regex/TDFA.hs#L35

The Haddock documentation contains an example with a escape sequence in a string, and there is no extra escaping: https://haskell-haddock.readthedocs.io/en/latest/markup.html#examples
```haskell
-- >>> putStrLn "foo\nbar"
-- foo
-- bar
```

I think this should be considered a haddock bug rather than a bug here, do you agree @s-and-witch ?

**Comment by andreasabel** [comment]
Ok, I played a bit with the problem.  The crux seems to be the explicit code block annotations `@...@`: https://github.com/haskell-hvr/regex-tdfa/blob/693a7f8e8df9a472e63ccb80afacc7e94138d6b8/lib/Text/Regex/TDFA.hs#L34-L53
It seems that removing them would fix the formatting.  After all, `>>>` is already indicating code!

**Comment by andreasabel** [comment]
@s-and-witch : Please check the new rendering at https://hackage.haskell.org/package/regex-tdfa-1.3.2.1/candidate/docs/Text-Regex-TDFA.html

**Comment by andreasabel** [comment]
Ok, then I'll release the fix!
